### ISSUE TITLE
SVG Files with No Stop and Xlink:href don't work

### ISSUE THREAD

**Issue by leogdion** [swhitty/SwiftDraw#1]
Sample SVG File Attached
[apple.svg.zip](https://github.com/swhitty/SwiftDraw/files/4838769/apple.svg.zip)

**Comment by leogdion** [comment]
I posted a start to a fix here:
https://github.com/brightdigit/SwiftDraw/tree/feature/fix-references

**Comment by swhitty** [comment]
Thanks for reporting the issue @leogdion.  I have pushed a localised fix that addresses just the LinearGradient case. I suppose I need to look at a more generalised solution as any element could possibly reference a def.

![Simulator Screen Shot - iPhone 11 Pro - 2020-06-27 at 11 53 59](https://user-images.githubusercontent.com/867662/85912126-85906400-b86d-11ea-9dd0-9ba71ab21a33.png | width=320)

**Comment by swhitty** [comment]
Latest release
https://github.com/swhitty/SwiftDraw/releases/tag/0.7.2

**Comment by leogdion** [comment]
Yeah the result doesn't seem to be have the gradient there. I'm wondering if it has to do with `gradientUnits="userSpaceOnUse"` which would throw off the gradient coordinates.

**Comment by swhitty** [comment]
Thanks @leogdion. `0.7.3` adds support for `gradientUnits="userSpaceOnUse"`

<p align="center">
<img src="https://user-images.githubusercontent.com/867662/87236660-0a16e100-c42f-11ea-982e-0952f54d7fc1.png" width="40%" />
</p>
