### ISSUE TITLE
Svg image seems to be blurry and doesn't parse some part properly when imageView frame is small

### ISSUE THREAD

**Issue by dpliushchaiIOS** [swhitty/SwiftDraw#12]
It seems that svg image is blurry & doesn't parse some part properly (take a look at "BET" in the beginning) if the image size is less than imageView size. It did not look ideally in previous versions but in 0.13.0 it looks really bad.

I tested on iPhone 11 IOS 15.6

 
![IMG_1117](https://user-images.githubusercontent.com/59007906/187441961-edfaf914-d8bb-420c-8daf-aa61cee9f894.PNG)

I also attached sample project and .svg image.
[SVG.zip](https://github.com/swhitty/SwiftDraw/files/9452949/SVG.zip)
![logo](https://user-images.githubusercontent.com/59007906/187442329-7c5fa13f-d4e5-4c3e-abdd-0d2305265095.svg)

**Comment by swhitty** [comment]
Thank you for the sample project.

[0.13.0](https://github.com/swhitty/SwiftDraw/releases/tag/0.13.0) introduced a regression where images rasterized to UIImage would be scaled twice.

This has been fixed on the `main` branch and will be included in the next release.

**Comment by dpliushchaiIOS** [comment]
Thank you so much!

**Comment by swhitty** [comment]
[0.13.1](https://github.com/swhitty/SwiftDraw/releases/tag/0.13.1) is now available
