### ISSUE TITLE
error build: Entry point (_main) undefined. for architecture x86_64

### ISSUE THREAD

**Issue by Azilla030** [swhitty/SwiftDraw#14]
I have two error the first is in the title and second one is:
"/Users/alexanderruder/Library/Developer/Xcode/DerivedData/W4U-Risikoapp-avswhmmknksifadrneimtyrnozkq/SourcePackages/checkouts/SwiftDraw/SwiftDraw/Parser.XML.StyleSheet.swift:167:16: error build: Cannot find type 'SwiftDraw' in scope

Thanks in advance

**Comment by swhitty** [comment]
Thanks for reporting this @Azilla030

May I ask which target are you trying to build? The SwiftDraw library or the swiftdraw command line executable?  Which version of a code are you using? And how are you building, spm, cocoa pods or Xcode?

I have experienced some similar errors myself — I think naming of the library and executable trigger a case fold issue in the latest compilers, but a clean build or recreating the schemes normally fixes it for me.

**Comment by Azilla030** [comment]
I try to integrate SwiftDraw Module in my Swift File the swift draw command line works fine I could generate a file.
What do you mean with "but a clean build or recreating the schemes normally fixes it for me" I'm new in Swift or in Mobile Development.

**Comment by swhitty** [comment]
Have you copy and pasted the code into your app?  It looks like the `SwiftDraw` module does not exist.

The best way to integrate with an existing app is to use Swift Package Manager like so;

<img width="1371" alt="packages" src="https://user-images.githubusercontent.com/867662/193511457-b12f152f-e4a1-4738-9805-2ee9940df73c.png">

<img width="1340" alt="dependency" src="https://user-images.githubusercontent.com/867662/193511484-f35afe13-9ff8-4c10-9b91-5bddd6b5933d.png">

Then you should be able to `import SwiftDraw` and use the public interface.
