### ISSUE TITLE
MacCatalyst support

### ISSUE THREAD

**Issue by FullQueueDeveloper** [swhitty/SwiftDraw#15]
Getting this error and others, related to Mac Catalyst support.

```
SwiftDraw/SwiftDraw/NSImage+Image.swift:67:29: error build: 'NSGraphicsContext' is unavailable in Mac Catalyst
```
<img width="390" alt="Screen Shot 2022-10-07 at 3 36 57 PM" src="https://user-images.githubusercontent.com/103295874/194640505-8fb7fbdc-85ee-4fbd-85b0-a99ce2f6d759.png">

**Comment by swhitty** [comment]
Thank you for the fix @FullQueueDeveloper.

Release [0.13.2](https://github.com/swhitty/SwiftDraw/releases/tag/0.13.2) is now available and including Mac Catalyst support.

**Comment by FullQueueDeveloper** [comment]
Thanks @swhitty, I'm using `0.13.2` successfully in my project.
