### ISSUE TITLE
iOS error from Examples/Samples.bundle/key

### ISSUE THREAD

**Issue by radutx** [swhitty/SwiftDraw#18]
Hello,

I started to use SwiftDraw library in an iOS project via SPM for SVGs. It works perfectly but there is an error showing in Xcode 14.2 in the top bar:
`Couldn't load project at: /Users/.../Library/Developer/Xcode/DerivedData/...-aeethnaxrwfkszbqqkkoiqbkxasp/SourcePackages/checkouts/SwiftDraw/Examples/Samples.bundle/key
`

The error is not blocking the build, is just sitting there waiting to be fixed.

Is there any solution to it? Or can you remove the "key" asset as it seem to cause the error?

**Comment by swhitty** [comment]
Thank you for reporting this 🙏🏻
The message should no longer be visible in [0.14.1](https://github.com/swhitty/SwiftDraw/releases/tag/0.14.1)
