### ISSUE TITLE
Failure: No valid content found

### ISSUE THREAD

**Issue by manicslothpdx** [swhitty/SwiftDraw#21]
I am trying to convert an SVG to SFSymbol. The other formats work i.e. PDF, PNG, etc. but when I try to use the sfsymbol option, i get the error "Failure: No valid content found." Are there parameters the SVG has to meet before it can be converted into an SFSymbol?

**Comment by swhitty** [comment]
The SVG must contain at least one shape that includes a path before it can be converted. Are you able to supply a sample SVG that fails with this error?

**Comment by manicslothpdx** [comment]
Thanks for the quick reply. Your comment led me in the right direction. I needed to "Export Selection... " in Illustrator instead of plain Export.
