### ISSUE TITLE
How to maintain inserts from svg file

### ISSUE THREAD

**Issue by vladzz** [swhitty/SwiftDraw#22]
We need to maintain inserts from Figma designs like so:
![image](https://github.com/swhitty/SwiftDraw/assets/197596/928b8bec-a4cb-4d5c-adc8-d12685c5fe53)

However when we use swiftdraw to convert all the svg's assets given to us it seems to move those inserts. Unless we set them manually per file.

Original SVG File:
![check](https://github.com/swhitty/SwiftDraw/assets/197596/eda5434f-d1fa-4c6a-a953-46b30d0da4f4)

Swiftdraw generated sfsymcols
![check](https://github.com/swhitty/SwiftDraw/assets/197596/c55f1426-3ce7-4b83-a98b-bc3d5ea2bae7)

Is there a way we can get swiftdraw to maintain the inserts from the original SVG that was generated from the figma design?

**Comment by vladzz** [comment]
> move

emo

**Comment by anodetamer** [comment]
I face the same problem. How did you solve this?

**Comment by swhitty** [comment]
By default `auto` insets are applied, but you can supply your own. To remove all insets use:

`--insets 0,0,0,0`

**Comment by vladzz** [comment]
Thanks @swhitty but what if I just want it to replicate the insets from the original SVG? It doesn't seem to do that? The insets it adds with auto are completely different to the original file.

**Comment by swhitty** [comment]
You should use `--insets 0,0,0,0` to align the edges of the original SVG to the SFSymbol guides.

Let's use [key.svg](https://github.com/swhitty/SwiftDraw/blob/main/Samples.bundle/key/key.svg) as an example. The SVG includes a canvas size of 256x256. The paths within the SVG are positioned within the canvas like so;

<img width="512" alt="key" src="https://github.com/swhitty/SwiftDraw/assets/867662/98a26a54-5d1e-4ea8-a380-d97bbc710323">

## --insets auto

By default SwiftDraw uses `--insets auto` to detect these insets and align those positions to the SFSymbol guides;

<img width="500" alt="key-auto" src="https://github.com/swhitty/SwiftDraw/assets/867662/ca694cb2-ba27-4106-84e8-6c4e5a5076dd">

## --insets 0,0,0,0

Supplying  `--insets 0,0,0,0` aligns the edges of the SVG canvas to these guides, preserving the padding within the SVG itself.

<img width="490" alt="key-zero" src="https://github.com/swhitty/SwiftDraw/assets/867662/5fc2e30e-b611-48b6-ba51-664b140a95e2">
