### ISSUE TITLE
Base64 encoded images are inverted and not positioned or correctly sized

### ISSUE THREAD

**Issue by teejayhh** [swhitty/SwiftDraw#26]
Hello, I have an svg which we generate on our server side which renders great in web browsers but when loading it in our app (through this cool package) we run into a few issues. The svg basically just contains positioned image tags with a base64 encoded href. 

```
<image width="68.39999999999999" height="55.199999999999996" x="234.8" y="439.9" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMoAAACkCAYAAADWm7GCAACyBkl .....></image>
```
the output image loads all the images but they are not positioned/sized and they seemed to be flipped on their heads. I created a test file where I took out a few things but it should show the issue.

![test](https://github.com/swhitty/SwiftDraw/assets/2525235/65f63d71-18da-4bfb-a7c3-e7bec2f1967a)

<img width="423" alt="Screenshot 2023-09-25 at 5 14 56 pm" src="https://github.com/swhitty/SwiftDraw/assets/2525235/79677478-4baa-4dc7-aac2-73ae2c39a5f9">

Maybe I am using it wrong but I cant see how. 

Cheers from Sydney

**Comment by swhitty** [comment]
🙏🏼 thank you for reporting this @teejayhh the fix has been merged to `develop` and will be included in the next release. Please do let me know if there are any more issues.
