### ISSUE TITLE
Package Doesn't Build for Swift 5.9

### ISSUE THREAD

**Issue by VakhoKontridze** [swhitty/SwiftDraw#35]
Hey!

Package doesn't seem to build in a project with Swift 5.9 due to the Linker issues.

<img width=400 src="https://github.com/swhitty/SwiftDraw/assets/57289621/f7dd1e32-a669-4ad0-ab32-37d53c9d271e">

<img src="https://github.com/swhitty/SwiftDraw/assets/57289621/00469b7a-4c8a-4d4c-87d6-42fa57f13a10">

As a workaround, I forked the repository. When I comment out `.executable(name: "swiftdraw", targets: ["CommandLine"])` line in `Package.swift`, it builds fine.

<img src="https://github.com/swhitty/SwiftDraw/assets/57289621/25f2e6c4-252e-4585-ae1b-a0be1c810e11">

**Comment by swhitty** [comment]
Thank you for reporting the issue @VakhoKontridze 

I have managed to recreate it, it looks like Xcode 15 offers to link against the command line tool - `swiftdraw (Executable)` by default which will not link:

<img width="728" alt="Screenshot 2023-12-13 at 5 13 31 pm" src="https://github.com/swhitty/SwiftDraw/assets/867662/8a53d0bc-e124-4d3f-a91e-7096ad0f1813">

Make sure you only link against the `SwiftDraw (Library)` and it will work.
