### ISSUE TITLE
Base64 encoded images are cut off

### ISSUE THREAD

**Issue by andrewjmead** [swhitty/SwiftDraw#40]
Hey, Simon.

First, thanks for the library. It's been quite helpful.

I'm using SwiftDraw to render a SVGs that are user uploaded. I noticed a problem with SVGs that have base64 encoded image data embedded in them. They're getting cut off no matter how I seem to configure it.

Most SVGs work just fine. A few, this one included, get clipped. Any thoughts on this?

Thanks!

**Original SVG:**

[icon.svg.zip](https://github.com/swhitty/SwiftDraw/files/15382047/icon.svg.zip)

![Screenshot 2024-05-20](https://github.com/swhitty/SwiftDraw/assets/2992789/2a88c0da-a200-4927-9c11-a0d302b3a420)

**SwiftDraw rendered version**

![Screenshot 2024-05-20](https://github.com/swhitty/SwiftDraw/assets/2992789/f42f2085-e049-44bf-a01c-3fb4c1a77e21)

**Demo code I'm working with:**

```swift
let svgURL = URL(string: "https://ps.w.org/independent-analytics/assets/icon.svg")!
let svg = SVG(fileURL: svgURL)
let desiredSize = CGSize(width: 96, height: 96)
self.image = svg?.rasterize(with: desiredSize) // I've also tried with no "with"
```

**Comment by swhitty** [comment]
Thank you for reporting the defect @andrewjmead 🙏🏻.

It should now be fixed on `develop` branch and will be included within the next release.
