### ISSUE TITLE
SVG conversion incomplete

### ISSUE THREAD

**Issue by paulschmidt** [swhitty/SwiftDraw#43]
Converting this .svg image of the American flag to image and saving as .png only shows one star
![us](https://github.com/swhitty/SwiftDraw/assets/6090139/8a686e65-eb05-4079-a044-0bf3032f81a8)
![us](https://github.com/swhitty/SwiftDraw/assets/6090139/40c886f7-c242-4d46-8d29-10c1dd7b47a4)

**Comment by swhitty** [comment]
Thank you for reporting this @paulschmidt.

It has been fixed on `main` branch and will be included in the next release.
