### ISSUE TITLE
[parsing error] output.svg  error: invalidAttribute(name: "display", value: "block"

### ISSUE THREAD

**Issue by alpennec** [swhitty/SwiftDraw#53]
Hello,

I'm trying to parse an SVG file (attached) but I get the following error

`[parsing error] output.svg  error: invalidAttribute(name: "display", value: "block")`

I think the issue is [here](https://github.com/swhitty/SwiftDraw/blob/fb79a0a67dc1196868aa29e7b0bf894683a51219/SwiftDraw/Parser.XML.SVG.swift#L65) but I haven't been able to find how to fix that.

Can you please have a look?
Thanks
Axel

![output](https://github.com/user-attachments/assets/3d35e793-2ec7-4f92-947f-ae37c9d366fc)

**Comment by swhitty** [comment]
Thank you for reporting the issue 🙏🏻

It has been fixed on the `main` branch by https://github.com/swhitty/SwiftDraw/pull/54

**Comment by alpennec** [comment]
Thanks!

**Comment by uy** [comment]
Hi @swhitty I still got this error. Is there any workaround?

**Comment by swhitty** [comment]
I have not published a new version with the fix can you try that? [0.18.1](https://github.com/swhitty/SwiftDraw/releases/tag/0.18.1)

**Comment by uy** [comment]
@swhitty yes! now it work like a charm 👏
