### ISSUE TITLE
Internal stylesheet support?

### ISSUE THREAD

**Issue by samizdatco** [swhitty/SwiftDraw#6]
At the moment SwiftDraw only seems to support style attributes that are set directly on SVG elements. Many tools create SVG files with an embedded stylesheet and rely on the style cascade to apply them to the elements. I can imagine this would be a significant undertaking, but it would be a great compatibility improvement if both types of files could be rendered. 

For instance, here are two 'identical' SVGs that differ only in terms of where their styles live:
> ### inline styles
> ![inline](https://user-images.githubusercontent.com/469523/180669595-444ca88a-5e06-4a28-800c-038304f97679.svg)

> ### internal stylesheet
> ![internal](https://user-images.githubusercontent.com/469523/180669597-3f6e029c-80ba-468d-939c-601745f7e9a7.svg)

SwiftDraw produces very different output when rendering them though:
<img width="885" alt="image" src="https://user-images.githubusercontent.com/469523/180669678-abf460f1-57b8-485f-91ee-b709184cbeca.png">

**Comment by swhitty** [comment]
While SwiftDraw probably can't full support all selectors (e.g. descendents) within stylesheets, would it be useful if a small subset were supported?  Simple class and element matching is probably simple enough to implement.

**Comment by samizdatco** [comment]
The use case I have in mind is being able to work with SVG produced by Illustrator, Figma, and the like. As far as I can tell, the embedded stylesheets they produce don't get any fancier than using class- and id-based selectors. So the subset you're considering seems like it would be a huge compatibility boost.

**Comment by swhitty** [comment]
Great, I will look to implement this in the next version.

**Comment by swhitty** [comment]
Release [0.12.0](https://github.com/swhitty/SwiftDraw/releases/tag/0.12.0) adds basic support for stylesheets.
