### ISSUE TITLE
Parsing error missingAttribute(name: "offset")

### ISSUE THREAD

**Issue by 2n** [swhitty/SwiftDraw#9]
Microsoft has released a huge Emoji set as open source.
https://github.com/microsoft/fluentui-emoji

For each Emoji, three SVG files "Color", "Flat", and "High Contrast" and a PNG image "3D" are available.
SwiftDraw seems to fail to convert most SVGs of type "Color".
The error messages are all `parsing error missingAttribute(name: "offset")`.

Try [face_with_open_mouth_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Face%20with%20open%20mouth/Color/face_with_open_mouth_color.svg).

```sh
$ swiftdraw face_with_open_mouth_color.svg --format png --size 512x512
[swiftdraw] parsing error missingAttribute(name: "offset")
Failure
```

The only "Flat" type that fails to convert is [eleven_oclock_flat.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Eleven%20oclock/Flat/eleven_oclock_flat.svg).

```sh
$ swiftdraw eleven_oclock_flat.svg --format png --size 512x512
[swiftdraw] parsing error missingAttribute(name: "offset")
Failure
```

In addition, a few of the "Color" types are successfully converted, but most of them are not converted correctly.
For example, the conversion of [avocado_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Avocado/Color/avocado_color.svg) results in a black cross section.
(This may be a separate issue from the above.)

![swiftdraw_avocado](https://user-images.githubusercontent.com/52402075/184444368-10c9f095-467c-40e2-b123-a5d11f27522b.png)

I'm not sure if you plan to support such complex SVGs, but I'm reporting this just in case.

**Comment by swhitty** [comment]
Thank you @2n for the bug report.  

Version [0.10.0](https://github.com/swhitty/SwiftDraw/releases/tag/0.10.0) includes support for radial gradients with a few other bug fixes to render these SVGs.

The more complex `<filter>` tags are not supported and I'm not sure if they ever will be. (Although they could map to `CIFilter` I suppose...)

**Comment by 2n** [comment]
Thanks again for the quick bug fix!

I have understood the difficulty of supporting `<filter>` tags.
That avocado looks good enough.

Thank you for your time despite your busyness.

**Comment by swhitty** [comment]
No problem, more than happy to look into supporting more of the SVG standard.

FYI the mainline branch now includes better support for the radial gradients in these SVGs.

<img src="https://user-images.githubusercontent.com/867662/184529494-26a15b75-cf14-4186-8e87-a1d7009db088.png" width="160" /><img src="https://user-images.githubusercontent.com/867662/184529498-3e43e044-5ed6-4b3b-bca7-ac19339a8941.png" width="160" />

**Comment by 2n** [comment]
Wow, that's great!
Those are even closer to the original look.
I can't wait to try the next release.

**Comment by swhitty** [comment]
Now available in [0.10.1](https://github.com/swhitty/SwiftDraw/releases/tag/0.10.1)

**Comment by 2n** [comment]
Thanks for the great work!

The PNG format output is correct, but the output Swift code draws strange images in the iOS simulator.
Only the face outline is drawn at the specified size, and the actual image is drawn upside down in the lower left corner at the original size.
(This seems to happen only with the newly supported SVG.)

![swiftdraw_0 10 1_1](https://user-images.githubusercontent.com/52402075/184592636-fdc03ae9-2f0d-4780-bf7e-d344b3671153.png)

***

The following error occurs in a very small percentage of SVGs.
([grapes_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Grapes/Color/grapes_color.svg))

```sh
$ swiftdraw grapes_color.svg --format png
[swiftdraw] parsing error missingAttribute(name: "stop-color")
Failure
```

***

Below are cases where there are still differences from the original.

In some Emojis, paths for highlighting is clearly drawn.
([ghost_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Ghost/Color/ghost_color.svg), [teddy_bear_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Teddy%20bear/Color/teddy_bear_color.svg), [snake_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Snake/Color/snake_color.svg), [two-hump_camel_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Two-hump%20camel/Color/two-hump_camel_color.svg))

![swiftdraw_0 10 1_2](https://user-images.githubusercontent.com/52402075/184593001-81a2f887-5994-42a7-9e4f-910619ee6204.png)

In some Emojis, some parts are not drawn.
([sleepy_face_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Sleepy%20face/Color/sleepy_face_color.svg), [spider_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Spider/Color/spider_color.svg), [two_oclock_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Two%20oclock/Color/two_oclock_color.svg), [petri_dish_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Petri%20dish/Color/petri_dish_color.svg))
![swiftdraw_0 10 1_3](https://user-images.githubusercontent.com/52402075/184593204-71a342e6-e490-4379-a399-aedf344acbe2.png)

This is a rare case.
([star-struck_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Star-struck/Color/star-struck_color.svg))
![swiftdraw_0 10 1_4](https://user-images.githubusercontent.com/52402075/184593252-005dc213-0fa1-4436-9c8b-52ffc127142a.png)

I understand that perfect support for Microsoft's new Emoji set is not the goal of this library, but I hope this helps in some small way to improve this library.

**Comment by 2n** [comment]
Great work!

Now high quality emojis display wonderfully on the iOS simulator.
It's really really great.

I think the command line option to hide elements where unsupported filters are used is a good idea.
If this option is implemented, it may be even better to echo warnings when converting contain unsupported filters.

```sh
// like this...
$ swiftdraw snake_color.svg --format png
Created: /Users/***/***/snake_color.png
Warning: <feGaussianBlur> filter in this SVG file is not supported. You can hide these elements with [--blabla] option.
```

***

The following is a small request not related to this issue.
If there are no problems, please consider adopting them.

***

Just as `dash-separated-name.svg` becomes `svgDashSeparatedName(size:)` in the conversion to Swift code, it might be useful if `snake_case_name.svg` becomes `svgSnakeCaseName(size:)` as well.

***

The converted Swift code has two methods, `svgFileName(size:)` and `drawSVG(in:scale:)`, the latter always having the same name.
Combining multiple Swift code into one file will naturally result in a compile error of `Invalid redeclaration of 'drawSVG(in:scale:)`.
I thought it would be more convenient if the name of `drawSVG(in:scale:)` was `drawFileName(in:scale:)` containing the file name.

```swift
// grapes.svg
extension UIImage {
  static func svgGrapes(size: CGSize = CGSize(width: 32.0, height: 32.0)) -> UIImage {
    // ...
  }

  private static func drawSVG(in ctx: CGContext, scale: CGSize) {
    // ...
  }
}

// snake.svg
extension UIImage {
  static func svgSnake(size: CGSize = CGSize(width: 32.0, height: 32.0)) -> UIImage {
    // ...
  }

  // Invalid redeclaration of 'drawSVG(in:scale:)'
  private static func drawSVG(in ctx: CGContext, scale: CGSize) {
    // ...
  }
}
```

**Comment by 2n** [comment]
There were still a few cases where some parts were not drawn.

[smiling_face_with_smiling_eyes_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Smiling%20face%20with%20smiling%20eyes/Color/smiling_face_with_smiling_eyes_color.svg)
[yawning_face_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Yawning%20face/Color/yawning_face_color.svg)
[worried_face_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Worried%20face/Color/worried_face_color.svg)
[troll_color.svg](https://github.com/microsoft/fluentui-emoji/blob/main/assets/Troll/Color/troll_color.svg)

![swiftdraw_0 10 2](https://user-images.githubusercontent.com/52402075/184874710-55d98505-a3e3-4d5c-a45e-1525b2518a29.png)

**Comment by 2n** [comment]
I must apologize for the serious mistake.
The images I have been using for comparison as originals were 3D rendered images from a different source than SVG.
I assumed that the PNG images included in the library were exported SVGs.

The clay animation-like texture and realistic three-dimensionality of the emojis I used for comparison is not originally available in SVG.
Comparing again with Figma's output, SwiftDraw appears to work almost perfectly, except for unsupported filters and some missing parts.

![swiftdraw_3d_svg](https://user-images.githubusercontent.com/52402075/185016080-953d948c-93fd-4fc1-bbfb-b02f580ab33c.png)

My deepest apologies for my silly mistake.

**Comment by swhitty** [comment]
Oh good to know.

[0.11.0](https://github.com/swhitty/SwiftDraw/releases/tag/0.11.0) includes support for stroking a path with radial gradients (fixes the latest issues).  It also includes suggested changes for `snake_case` filenames and `drawFileName()`.

Also a new `Image.Options.hideUnsupportedFilters` allows clients to optionally hide elements with unsupported filters.

**Comment by 2n** [comment]
Many thanks for your work.
Is the command line tool not included in the latest release?

**Comment by swhitty** [comment]
It is uploaded now — was being notarized.

**Comment by 2n** [comment]
The latest version works wonderfully.
Thanks so much for your hard work and adopting my suggestions.

I feel very fortunate to have found your library through a web search.
